#!/bin/bash

# Copyright (C) 2025 ITlopa
# The Ituxalien Script language (written in Bash)

evaluate() {
    local expression="$1"
    echo $((expression))
}

# Start C code
echo -e "// Generated by Itux Script compiler. Don't modify!\n#include <stdio.h>\n\nint main() {\n" > output.c

while true; do
    echo -n "> "
    read line

    if [[ "$line" =~ ^let\ ([a-zA-Z_][a-zA-Z0-9_]*)\ =\ (.*)$ ]]; then
        var_name="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"
        echo -e "    int ${var_name} = ${value};\n" >> output.c
    fi

    if [[ "$line" =~ ^string\ ([a-zA-Z_][a-zA-Z0-9_]*)\ =\ (.*)$ ]]; then
        var_name="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"
        echo -e "    const char* ${var_name} = \"$value\";\n" >> output.c
    fi

    if [[ "$line" =~ ^print\ (.*)$ ]]; then
        value="${BASH_REMATCH[1]}"
        echo -e "    printf(\"$value\");\n" >> output.c
    fi

    if [[ "$line" == "exit" ]]; then
        break
    fi
done

# End C code
echo -e "    return 0;\n}" >> output.c
